### ISSUE TITLE
always getting an empty index.yaml

### ISSUE THREAD

**Issue by sbose78** [otaviof/chart-streams#1]
```
apiversion: v1
generated: 2019-12-12T17:17:10.268471-05:00
entries: {}
publickeys: []
```

**Comment by sbose78** [comment]
@otaviof @isutton

**Comment by otaviof** [comment]
@sbose78 we gonna need more information on what you're doing. Could you share the exact steps you've take to reproduce this? :-)

**Comment by sbose78** [comment]
I'm running the server as  `./build/charts-streams server` . I see it takes the default config.

**Comment by sbose78** [comment]
I fixed a panic issue at startup if the relativeDir wasn't specified. Even after that, when I hit the index.yaml endpoint, I keep getting empty index.yaml

**Comment by isutton** [comment]
> I fixed a panic issue at startup if the relativeDir wasn't specified. Even after that, when I hit the index.yaml endpoint, I keep getting empty index.yaml
> 
> ```
> ./build/chart-streams serve
> INFO[0000] Starting server with config: '&config.Config{RepoURL:"https://github.com/helm/charts.git", RelativeDir:"mycharts", CloneDepth:1, ListenAddr:":8080"}' 

For clarity, the value of `RelativeDir` in this particular case should be `stable`, which is the directory in the repository specified in `RepoURL` where chart-streams should index its contents.
